### ISSUE TITLE
Not `ACCEPTABLE`

### ISSUE THREAD

**Issue by vcdev87** [miroslavpejic85/mirotalk#56] opened 2021-07-28 18:13 UTC
`Reference`:
1. https://github.com/miroslavpejic85/mirotalk/pull/52
2. https://github.com/miroslavpejic85/mirotalk/commit/468353441bb9a1c663d728b059aa8907075cbef8

Hi @miroslavpejic85 @Jaideep25 ! 👍 💯 
I am `very` disappointed now. I worked `on` migration of `docker-compose` to `docker compose` and put PR to review for maintainer. 🥇  
You say `PR` is no good even if instructions are clear: 
1. `docker-compose` is no longer needed mean `less depencies` needed to startup this `PROJECT` for beginners who only need `docker` and no need install `docker-compose` 🎸 . Instead of us having technical discussion about this, main`tainer bans` me as `contribrutor` from making comments 🆘  Also I see `maintainer` copied `my work` into his `OWN COMMIT` instead of merge PR!! `See` reference 2 above! 🆘  🎸 🕺 
I hope to `have discussions on this`.
3. Thank you.

**Comment by miroslavpejic85** [comment] 2021-07-28 18:27
Hy @vcdev87 
The problem is another, I thank you for your precious contribution, initially I accepted your PR, but then there were discussions etc. where we did not understand each other, so I close this issue once again, and I hope you find another project to contribute to, since you have also expressly written it in your profile ;) Good luck, and thanks for everything.
And let's close here.

**Closed** 2021-07-28 18:28 UTC
