### ISSUE TITLE
Video & Audio

### ISSUE THREAD

**Issue by FrosTechnology** [miroslavpejic85/mirotalk#91] opened 2022-03-07 19:24 UTC
After there is 3 or more participants the video will glitch out for everybody. And sometimes the audio also glitches out and makes it impossible for the others to hear you. Please fix.

**Comment by miroslavpejic85** [comment] 2022-03-07 19:48
Hello @RobloxianLua, 
- Has this happened recently or did you always have this problem?
- Does it happen by chance when you use the Safari browser? 
- Could you explain me the steps to reproduce, the browsers and devices involved? 
Thank you.

**Comment by RobloxianLua** [comment] 2022-03-08 00:44
I always have the problem when I am using MiroTalk with my friends. I
really wanted to ditch zoom but it’s hard to do it this way. Also people
gets randomly kick out. Thank you for getting back with me so fast and
actoully care about the project. I really hope it’s gonna fix soon. It
happens on any device. I use chrome. Also happens on other browsers.

**Comment by miroslavpejic85** [comment] 2022-03-08 07:59
In case you can try the SFU version of MiroTalk:

- Live demo: https://sfu.mirotalk.org/
- Repo: https://github.com/miroslavpejic85/mirotalksfu

It supports a lot more users, and should be a good Zoom alternative. 
Thanks to you!

**Comment by RobloxianLua** [comment] 2022-03-11 18:39
I did, but I cannot host it. I am using glitch.me to host it normal version
works but SFU takes forever to start

**Comment by miroslavpejic85** [comment] 2022-03-12 10:11
Hello @RobloxianLua,
I mean try my demo, as far as the deployment is concerned it's a whole other story :) 
I don't know glitch.me, [MiroTalk SFU](https://github.com/miroslavpejic85/mirotalksfu) usually needs to be deployed on DigitalOcean, Amazon AWS ec2 ...

## Regarding MiroTalk P2P

I think all of this is due by socket.io disconnections.

The cause of socket.io disconnections you can read here: 

- disconnect-detection: https://socket.io/docs/v4/how-it-works/#disconnection-detection
- Server-side: https://socket.io/docs/v4/server-socket-instance/#disconnect
- Client-side: https://socket.io/docs/v4/client-socket-instance/#disconnect

So the Server every 25 seconds (pingInterval) send a ping to the connected clients to see if is reachable
If the client not reply with the pong after 20 seconds (pingTimeout), for the server this client is dead.

The reason fo the client disconnection you can see in the server logs: https://github.com/miroslavpejic85/mirotalk/blob/master/app/src/server.js#L375

The reason can usually be: `transport close` where on the documentation it says:

> The connection was closed (example: the user has lost connection, or the network was changed from WiFi to 4G)

So I think it doesn't depend on MiroTalk, but on reachability, network stability, and external factors.

**Comment by thetwosents** [comment] 2022-04-19 14:57
Gather.town does a great job with multiple participants and keeping the load off of the server. Just passing on to anyone at Miro for this.

**Comment by miroslavpejic85** [comment] 2022-05-18 10:35
it should be fixed in: https://github.com/miroslavpejic85/mirotalk/commit/76b340dde3b8253b15402a5cd963f8c570e865c3

**Comment by AdrianaDJ** [comment] 2022-06-02 10:46
> Hello @RobloxianLua,
> 
> * Has this happened recently or did you always have this problem?
> * Does it happen by chance when you use the `Safari` browser?
> * Could you explain me the steps to reproduce, the browsers (updated to the latest version) and devices involved?
> * Are you trying it from the same device or from different devices?
> 
> NB: The quality of the call is inversely proportional to the number of participants in the call and available bandwith.
> 
> Thank you.

Try connecting via lan or ethernet or via bluetooth connection. Your dial up connection doesnt support the amount of bits and samples in the stream hence causing latency and remember there is alot of code in video and audio and visuals. Try using differents sizes of TV screens then ull see how it effects your quality, its all about the bits per second, depending on what your streaming, the compressed code your stream and network.  If your streaming to the web or radio keep it to 128.  Especially when more people are joining a stream. Also, try using a different audio setup or sound card, Contact me if ur struggling I can help.

**Comment by miroslavpejic85** [comment] 2022-06-03 07:43
> > Hello @RobloxianLua,
> > 
> > * Has this happened recently or did you always have this problem?
> > * Does it happen by chance when you use the `Safari` browser?
> > * Could you explain me the steps to reproduce, the browsers (updated to the latest version) and devices involved?
> > * Are you trying it from the same device or from different devices?
> > 
> > NB: The quality of the call is inversely proportional to the number of participants in the call and available bandwith.
> > Thank you.
> 
> Try connecting via lan or ethernet or via bluetooth connection. Your dial up connection doesnt support the amount of bits and samples in the stream hence causing latency and remember there is alot of code in video and audio and visuals. Try using differents sizes of TV screens then ull see how it effects your quality, its all about the bits per second, depending on what your streaming, the compressed code your stream and network. If your streaming to the web or radio keep it to 128. Especially when more people are joining a stream. Also, try using a different audio setup or sound card, Contact me if ur struggling I can help.

Hi AdrianaDJ, I thank you for the answer.

**Comment by miroslavpejic85** [comment] 2022-06-03 09:24
The disconnection issue seems to be only on railway.app, tested also with 2 participants on Heroku - Amazon AWS ec2... after `10 minutes` the peers don't disconnect from the room.

I asked if railway.app can take a look.

<img width="957" alt="railway" src="https://user-images.githubusercontent.com/70838434/171827027-49ba29e9-6470-4873-a338-337bd1212b74.png">

On Heroku seems all ok.

<img width="957" alt="heorku" src="https://user-images.githubusercontent.com/70838434/171827050-6dc22d2f-5521-4daf-a84d-a7ff7af368e8.png">

**Comment by miroslavpejic85** [comment] 2022-06-09 10:56
Added a New instance of MiroTalk P2P as default on: https://p2p.mirotalk.org (no disconnections issue every 10 min), 
The problem is only on the railway.app platform (I opened a task).

**Closed by miroslavpejic85** 2022-06-09 10:56 UTC
Labels: help wanted, good first issue, improvements
