### ISSUE TITLE
i love this mirotalk but there is some bugs

### ISSUE THREAD

**Issue by Nemra1** [miroslavpejic85/mirotalk#29] opened 2021-06-07 11:59 UTC
by luck i found this project and am very happy to find it
Now my plan is integrate to new stream php script with mysql but i found some bugs..idont no if you know about it
1-switch camera in mobile
not working with error and after searching i found this test link and i guess have same problem too
https://webrtc.github.io/samples/src/content/devices/input-output/
 2- clear chat is deleted locally only not for all users (im not sure if bug or not )
3- anyone can kick anyone even the visitors allowed to kick out the owner of room (im not sure if bug or not )
4- max 6 to 8 per room ( i know is peer to peer connection ) but if you just make any guide about integrate SFU to make it more wider for many users ..i will glad to help in this
--------------------
and finally ...your project is saved my time and i am very very happy to find it after long search.. i meet mediasoup and others projects but its takes long time to study and modifications....
------------------
in the end you help me and thank you very much Mr @miroslavpejic85 
 And everyone working on this amazing project.. ❤️❤️❤️

**Comment by Jaideep25** [comment] 2021-06-07 12:05
Hey @Nemra1 Welcome! Glad you liked @miroslavpejic85 's project! Actually, clear chat, kicking anyone isn't a bug, it's made like that! And I guess many can join cuz @miroslavpejic85  had shown me a screenshot that more people can join!

**Comment by Nemra1** [comment] 2021-06-07 12:08
@Jaideep25
but switch cam still important problem.. and really need some hand to help about that

**Comment by Jaideep25** [comment] 2021-06-07 12:10
Actually the switch cam works for a few people.... so I don't think it's a bug!

**Comment by Nemra1** [comment] 2021-06-07 12:20
@jaideep25
This is what im talk about
https://ibb.co/f4GQKQd

**Comment by Jaideep25** [comment] 2021-06-07 12:23
mm, may I know your OS in mobile, and which browser version?

**Comment by Nemra1** [comment] 2021-06-07 12:26
@Jaideep25
Huawei Y9 2020 with normally chrome browser from google play...also same problem for others browser like firefox 
this issue in mobile only but is working on desktop good

**Comment by miroslavpejic85** [comment] 2021-06-07 13:10
Hi @Nemra1, Thank you so much, i'm glad you like `mirotalk` and that you found it useful! ♥️
I'll answer you below, even if @Jaideep25 😇 something has already answered you.

1) I need to reproduce it to try to fix. For now it had never happened to me. But there is always the first time 🙂
2) Not a Bug, anyone `clear his` chat box conversation if want.
3) Not a Bug `anyone can feel free to kick the other` if they want, maybe in the future I could put some limitations, in the sense that only the `initiator` of the room can do certain actions. 
4) Yeah, Integrate `SFU` it would be very good goal! 💪

`Mirotalk` is not a finished project, it `will be improved` further and the `contributors are always welcome`! ♥️

**Comment by Nemra1** [comment] 2021-06-07 23:43
@miroslavpejic85 im glad to. Meet u sir..
1- yes same as for swipe button still showing same problem... So i have here - switch cam. In option panel and swipe button (same error) - android EMUi 9.1
About other os.. Tested on windows 10 with really camera device and virtual camera device.. That i was using to replace my cam with some video.. Is working fine.. I

**Comment by miroslavpejic85** [comment] 2021-06-08 09:38
Hi @Nemra1, It could be an incompatibility issue (os - browser version) or something else, with the official API being used to gain access to the webcam. I try to reproduce it, as soon as I have time. 😉

**Comment by Nemra1** [comment] 2021-06-08 12:35
@miroslavpejic85 best luck to you.. I hope you going to bulid it with cordova.. Is much easier for mobile os

**Comment by miroslavpejic85** [comment] 2021-06-09 09:11
Hi @Nemra1.
Try now to swap the camera, I `enabled` also the `error name` to see what can be the problem in your case:
if you have the error like `NotReadableError` : `Could not start video source`
It most commonly happens when the browser tries to access the webcam or mic but they're already in use (by Skype, etc.)
ref: https://blog.addpipe.com/common-getusermedia-errors/

**Comment by miroslavpejic85** [comment] 2021-06-13 11:18
@Nemra1 @Jaideep25 
I think for this task, I can't do anything about it, it doesn't seem like a mirotalk problem. 👀

**Comment by Nemra1** [comment] 2021-06-13 11:47
@miroslavpejic85 i will try tonight.. Thank you

**Comment by miroslavpejic85** [comment] 2021-06-14 19:49
Ok I `found` what the `problem` can be in certain cases like yours. 
It will be fixed as soon as I have more `free time` ;)

**Comment by miroslavpejic85** [comment] 2021-06-14 20:46
Hi @Nemra1 @Jaideep25 
Now you `should be able to swap camera` on `any devices`!

**Closed** 2021-06-18 09:17 UTC
Labels: improvements, question
